[book]
title = "Rust com Exemplos"
description = "Rust com Exemplos (RCE) é uma coleção de exemplos executáveis que ilustram vários conceitos e bibliotecas padrão da Rust."
author = "A Comunidade da Rust"
language = "pt"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/nazarepiedady/rust-com-exemplos"

[rust]
edition = "2021"
